name: 'crowdin-elixir-action'

description: 'Tries to manage and synchronize Crowdin'

inputs:
  source_file:
    description: 'Crowdin source file'
    required: true

runs:
  using: docker
  image: 'Dockerfile'
