name: 'crowdin-elixir-action'

description: 'Tries to manage and synchronize Crowdin'

inputs:
  token:
    description: 'Crowdin token'
    required: true

runs:
  using: docker
  image: 'Dockerfile'
