name: 'crowdin-elixir-action'

description: 'Tries to manage and synchronize Crowdin'

inputs:
  token:
    description: 'Crowdin token'
    required: true
  project-id:
    description: 'Crowdin project id'
    required: true
  source-file:
    description: 'Crowdin file to track'
    required: true

runs:
  using: docker
  image: 'Dockerfile'
